const {tables, tablePics} = require('./lib')
const {Command} = require('commander')

exports.tablesCommand = new Command()
    .name('tables')
    .description('Converts overview tables csv output to excel file')
    .allowUnknownOption()
    .action(tables)

exports.tablePicsCommand = new Command()
    .name('table-pics')
    .alias('tablepics')
    .description('Converts html output of xlsx file to pictures')
    .argument('[dx-folder]', 'The dx home folder (containing settings.txt file)', process.cwd())
    .allowUnknownOption()
    .action(tablePics)
